# Generated by Django 6.1.1 on 2026-09-11 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('databases', 'Databases'), ('behavioral', 'Behavioral'), ('backend', 'Backend / APIs'), ('frontend', 'Frontend'), ('devops', 'DevOps')], max_length=20)),
                ('priority', models.PositiveIntegerField(help_text='1 = highest priority')),
                ('average_score', models.FloatField()),
                ('recommended_topics', models.JSONField(blank=True, default=list)),
                ('recommended_resources', models.JSONField(blank=True, default=list)),
                ('practice_question_ids', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studyplan.studyplan')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='WeakArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('databases', 'Databases'), ('behavioral', 'Behavioral'), ('backend', 'Backend / APIs'), ('frontend', 'Frontend'), ('devops', 'DevOps')], max_length=20)),
                ('average_score', models.FloatField()),
                ('attempts', models.PositiveIntegerField()),
                ('is_weak', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['average_score'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
